--- #YAML:1.0
name: Finance-Bank-Norisbank
version: 0.01
author:
  - |-
    James Mastros, <james@mastros.biz>.  theorbtwo on perlmonks.org.
abstract: ! >-
  Bank Identification Code) of 
  
  Norisbank.  This is aliased to SWIFT as well.  (This returns the part of the
  SWIFT code that is the same for all Norisbank 
  
  branches.)
license: perl
requires:
  Data::Dumper: 0
  HTML::TableExtract: 0
  HTML::TreeBuilder: 0
  Locale::Object: 0
  POSIX: 0
  Time::Local: 0
  URI: 0
  URI::QueryParam: 0
  URI::URL: 0
  WWW::Mechanize: 0
provides:
  Finance::Bank::Norisbank:
    file: lib/Finance/Bank/Norisbank.pm
    version: 0.01
generated_by: Module::Build version 0.25
